@startuml
participant "<b>LDAP Server</b>" as LDAP_Server order 10
participant "<b>LDAP Collector</b>" as LDAP_Collector order 20
participant "<b>Morph-KGC</b>" as Morph order 30

skinparam sequenceMessageAlign center

Morph -> LDAP_Collector: HTTP GET /ldap.json

LDAP_Collector -> LDAP_Server: Connect
LDAP_Server --> LDAP_Collector: OK
LDAP_Collector -> LDAP_Server: Retrieve users
LDAP_Server --> LDAP_Collector: OK
LDAP_Collector -> LDAP_Server: Retrieve roles
LDAP_Server --> LDAP_Collector: OK
LDAP_Collector -> LDAP_Server: Retrieve groups
LDAP_Server --> LDAP_Collector: OK
LDAP_Collector -> LDAP_Server: Retrieve organizations
LDAP_Server --> LDAP_Collector: OK
LDAP_Collector -> LDAP_Server: Unbind and disconnect
LDAP_Server --> LDAP_Collector: OK

note over LDAP_Collector: Generate JSON

LDAP_Collector --> Morph: HTTP 200 OK
@enduml